server:
  port: 7070

local:
  year: 2024
  repo: ./local-repo
  index: ./local-index

google:
  credentials:
    file:
      path: '/Users/maxvolkel/__max/Finanzen/2024/credentials/client_secret.json'
  tokens:
    directory:
      path: tokens
  api:
    timeout: 60000
    # max allowed per request
    max-search-results: 500
